<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Entravel.Common\Entravel.Common.csproj" />
    <ProjectReference Include="..\Entravel.Contracts\Entravel.Contracts.csproj" />
    <ProjectReference Include="..\Entravel.Domain\Entravel.Domain.csproj" />
    <ProjectReference Include="..\Entravel.Data\Entravel.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
